### ISSUE TITLE
Configure a Default Parameter Set For New-AsBuiltReport

### ISSUE THREAD

**Issue by mattallford** [AsBuiltReport/AsBuiltReport.Core#13]
**Is your feature request related to a problem? Please describe.**
When running New-AsBuiltReport with no paramters specified, an error is shown because Powershell is not sure which parameter set to use:
`New-AsBuiltReport : Parameter set cannot be resolved using the specified named parameters.`

**Describe the solution you'd like**
Implement a default parameter set so the user is prompted for mandatory paramters if running New-AsBuiltReport without any parameters

**Describe alternatives you've considered**
Leaving the functionality as-is which means the user will receive an error if they try to run the cmdlet without any parameters as described above. This would be OK as the error message shown is relevant, but it might confuse powershell novice users.

**Comment by tpcarman** [comment]
Resolved in 6b858bf79ffefe24bd75add56391ee231df0ca01
