### ISSUE TITLE
Pass through authentication

### ISSUE THREAD

**Issue by southwej** [AsBuiltReport/AsBuiltReport.Core#20]
In some environments username/password is not allowed. Passthru authentication support would be nice. Not requiring username/password would be helpful.

**Comment by tpcarman** [comment]
I'm not sure I understand your issue. 

There is the `Credential` parameter which can be used with a stored credential.

```powershell
$creds = Get-Credential
New-AsBuiltReport -Report VMware.vSphere -Target vcenter.domain.local -Credential $creds
```

**Comment by tpcarman** [comment]
Stale issue. Please reopen if required.
