### ISSUE TITLE
Language templates

### ISSUE THREAD

**Issue by rebelinux** [AsBuiltReport/AsBuiltReport.Core#35]
**Is your feature request related to a problem? Please describe.**

It would be beneficial to add the option to generate the report in an available language. I don't know if it is achievable but maybe there could be a JSON file with the translations depending on the language. With the option for the user to create the JSON with the language of his choice based on a default english template

**Describe the solution you'd like**

- Command Example
  - New-AsBuiltReport -Report VMware.SRM -Target 192.168.5.2 -Format Word -Credential $cred (-Language French)

- Section Example
  - Section -Style Heading1 "$(Protection Groups JSON Variable)" {}

**Describe alternatives you've considered**

**Additional context**

**Comment by alagoutte** [comment]
Hi,

I like the idea too @tpcarman do you have an idea for make this ?

**Comment by tpcarman** [comment]
I'm currently experimenting with how support for other languages could potentially be implemented for AsBuiltReport. 

❗ This is not a commitment to adding this feature, I am simply working to determine if it would be feasible.
