### ISSUE TITLE
Option to export sample report

### ISSUE THREAD

**Issue by rebelinux** [AsBuiltReport/AsBuiltReport.Core#36]
**Is your feature request related to a problem? Please describe.**

It would be ideal to add an option to export the "Sample Report.html" as long as it is available in the Sample folder of the project.

**Describe the solution you'd like**

- Example Command
  - New-AsBuiltReport -Report VMware.SRM -OutputFolderPath /home/rebelinux/script -SampleReport

**Describe alternatives you've considered**

**Additional context**

**Comment by tpcarman** [comment]
Sample reports can already be provided within each module and linked from the `README.md` documentation. I don't see a compelling need to add this functionality to the `New-AsBuiltReport` cmdlet. I tend to think that if users wish to see a report, they will look at a sample available on GitHub and then download the module to generate an actual report against their own environment. I have not seen or heard of users downloading modules to simply generate a sample report. For these reasons, I do not see the benefit in implementing this feature at this time.
