### ISSUE TITLE
Allow parameters for New-AsBuiltConfig

### ISSUE THREAD

**Issue by jhofbauer** [AsBuiltReport/AsBuiltReport.Core#43]
Hello,

it is possible to allow paramters -Folderpath and -Filename for New-AsBuiltConfig?

We can specify this on New-AsBuiltReportConfig and it is very helpful if you want to fully automate the report generation. The New-AsBuiltConfig don't allow to specify this parameters and the outcome depends on the input choices made by the enduser.
This is an problem, if you want to use the generated configuration to generate the reports fully automated.

Best regards,
Jens

**Comment by tpcarman** [comment]
@jhofbauer  How are you expecting this to work? `New-AsBuiltConfig` is used to capture information via a series of questions. If you wanted to automate report generation then you run `New-AsBuiltConfig` first to capture the information and save the JSON file (e.g. MyInfo.json). 

Then use the saved JSON file with `New-AsBuiltReport -Report Vmware.vSphere -Target vcenter.lab.local -Credential $creds -AsBuiltConfigFilePath MyInfo.json`. 

Adding `FolderPath` and `Filename` parameters isn't ging to add any benefit. You're still going to have to answer the other questions to generate a JSON configuration file.
